#Load Libraries

library(caret)
library(party)
library(randomForest)
library(ggplot2)
library(plyr)
library(scales)
library(reshape)
library(stringr)
library(lubridate)
library(directlabels)
library(testthat)
library(ascii)
library(mi)
library(lubridate)
library(arm)
library(Amelia)
library(glmnet)
library(VIM)
library(doMC)
#library(Zelig)
registerDoMC(2)